```{r}
# Executa a amostragem casual simples para inventário florestal na região de nova lima mg
#Entrada: Parcela, árvore, fuste, espécie, CAP, altura
#Saida: fitossociologia, volumetria, parametros da amostragem, distribuição de altura e diamétrica 
```

```{r}
#bibliotecas e importações

library(openxlsx)
library(ggplot2)
library(dplyr)
options(OutDec = ".")

```

```{r}
#funções utilizadas

#importação de dados
ImportarDados <- function(){
 
  return(openxlsx::read.xlsx(file.choose()))
}

#Acrescenta Colunas de Dados: dap, AB, Vol
calcDAV <- function(DadosTemp){
  
  DadosTemp$DAP <- round(DadosTemp$CAP / pi, 2)
  DadosTemp$AB <- round((pi/40000) * (DadosTemp$DAP ^ 2), 5)
  DadosTemp$VTcc <- round(exp(-9.77830707 + 2.1472609409 * log(DadosTemp$DAP, exp(1)) + 0.7804098114 * log(DadosTemp$Altura, exp(1))),5)
  DadosTemp <- DadosTemp[, c(1, 2, 3, 4, 5, 7, 6, 8, 9)] #modificar ordem das colunas
  
  return(DadosTemp)
}

#calcula a tabela de volume por parcela
calcVolumeTab <- function(DadosTemp){
  
  DadosVol <- aggregate(round(DadosTemp$VTcc, 5), by=list(DadosTemp$Parcela), FUN=sum)
  colnames(DadosVol)[c(1,2)]<- c("Parcela","VTcc", "VolST")
  DadosVol$VolST <- round(DadosVol$VTcc * 1.5, 5)
  
  return(DadosVol)
}

#Recebe os parametros do inventário. Padrão: AreaParc=300, AreaTotal=2, erro=10, confi=90
receberParametros <- function(){
    
    #readline()
    AreaTotal <- 2 # as.numeric(readline("Digite a área total em hectares: ")) 
    AreaParc <- 300 # as.numeric(readline("Digite a área da parcela em m²: "))
    ErroMax <- 10 #as.numeric(readline("Digite o erro máximo admissível: "))
    Probabilidade <- 90 #as.numeric(readline("Digite o nível de probabilidade: ")) 
  
    return(data.frame(AreaTotal, AreaParc, ErroMax, Probabilidade)) 
      
}

#calcula o inverso de T bicaudal - equivalente ao INV.T.BC no excel
inv.t.bc <- function(p, gl) {
  invt <- qt(1-(((100-p)/100)/2),gl)
 
   return(invt)
}

#calcula os parametros do inventário
calcParamInventario <- function(DadosVol, Parametros){
    fatorEstereo <- 1.5
    ParamACS <- data.frame(
    Parâmetro = c("Área total", "Vol. Total Mensurado", "N. Parc. Possíveis", 
                   "Área da parcela", "N. Parc. Lançadas (n)", "Média", 
                   "Variância", "Desvio-padrão", "Valor de t",
                   "Erro Máximo Admissível", "Coeficiente de Variação", "Erro-padrão da média","Erro de amostragem",
                   "N. Parcelas Necessárias", "Vol. Mínimo", "Vol. Médio", "Vol. Máximo", "St. Mínimo", "St. Médio", "St. Máximo"  ),
   Valor = 0,
   
   Unidade = c("ha", "m³", "un", 
               "m²", "un","m³",
               "m³²", "m³", paste(as.character(Parametros$Probabilidade), "%"),
               "%", "%", "%", "%",
               "un","m³/ha", "m³/ha", "m³/ha",
               "st/ha", "st/ha", "st/ha")
   
   )
  
    #calcular cada parâmetro separadamente antes de passar para o dataframe
    #Variáveis Temporarias com a letra t neste contexto
      tMedia <- mean(DadosVol$VTcc)
      tDesvioPadrao <- sd(DadosVol$VTcc)
      tVariancia <- tDesvioPadrao ^ 2
      tCoefVariacao <-tDesvioPadrao / tMedia
      tValorT <- inv.t.bc(Parametros$Probabilidade, nrow(DadosVol)-1)
      tNumMaxParcelas <- as.integer(ceiling((Parametros$AreaTotal * 10000) / Parametros$AreaParc))
     
       #valor de erro padrao da media (amostra finita ou infinita)
      if (nrow(DadosVol)/tNumMaxParcelas > 0.02) {
        tErroPadMedia <- sqrt((tVariancia / nrow(DadosVol)) * (1 - (nrow(DadosVol) / tNumMaxParcelas)))
      } else {
        tErroPadMedia <- sqrt(tVariancia/nrow(DadosVol))
      }
      tErroPadMedia <- tErroPadMedia
      
      tErroAmostragem <- (tErroPadMedia * tValorT) / tMedia
      
      #valor de n (amostra finita ou infinita)
      if (nrow(DadosVol)/tNumMaxParcelas > 0) {
        tValorNn <- ((tValorT ^ 2) * (tCoefVariacao ^ 2)) / (((Parametros$ErroMax/100)^2) + (((tValorT ^ 2) * (tCoefVariacao ^ 2))/tNumMaxParcelas))
        
      } else {
        tValorNn <- ((tValorT ^ 2) * (tCoefVariacao ^ 2)) / (((Parametros$ErroMax/100)^2))
      }
      
      tValorNn <- as.integer(ceiling(tValorNn))
      tVolMed <- sum(DadosVol$VTcc) / (nrow(DadosVol)*(Parametros$AreaParc/10000))
      tVolMin <- tVolMed - tVolMed * tErroAmostragem
      tVolMax <- tVolMed + tVolMed * tErroAmostragem
      
      ParamACS$Valor <- c(round(Parametros$AreaTotal, 4), round(sum(DadosVol$VTcc), 5),   
                          tNumMaxParcelas, Parametros$AreaParc, nrow(DadosVol), round(tMedia, 5),
                          round(tVariancia, 5), round(tDesvioPadrao, 5), round(tValorT, 5),
                          round(Parametros$ErroMax,5), round(tCoefVariacao * 100, 5),
                          round(tErroPadMedia * 100, 5), round(tErroAmostragem * 100, 5),
                          round(tValorNn, 5), round(tVolMin, 5),
                          round(tVolMed,5), round(tVolMax, 5),
                          round(tVolMin * fatorEstereo, 5),
                          round(tVolMed * fatorEstereo, 5),
                          round(tVolMax * fatorEstereo, 5))

    return(ParamACS)
} 

#retorna a distribuição diamétrica
calcDistDiametrica <- function(DadosDiam){
  
  #monta a tabela de classes diametricas
  numClasses <- ceiling(max(DadosDiam$DAP)/5) - 1 #define a maior classe
  numDiametros <- data.frame() 
  
  contWhile <- 1
  while (contWhile <= numClasses){
  
    numDiametros <- rbind(numDiametros, (paste(contWhile * 5, "-",(1 + contWhile) * 5, sep = "")))
    contWhile <- contWhile + 1
  
  }
  
  #cria a tabela de classes
  colnames(numDiametros)[1] <- "Classe" #muda o nome da coluna
  DiamHisto <- hist(DadosDiam$DAP, breaks=seq(5,(1+numClasses)*5,5), plot=FALSE) #faz o histograma a cada 5 cm até o máximo
  numDiametros$Num <- cbind(DiamHisto[["counts"]])
  numDiametros$Num <- numDiametros$Num
  numDiametros <- data.frame(rbind(numDiametros, c("Total", sum(numDiametros$Num)))) #soma o total
  numDiametros[,2] <- sapply(numDiametros[,2], as.numeric)
  colnames(numDiametros)[2] <- "Num. Fustes" #muda o nome da coluna
  
  return(numDiametros)

}

#retorna a distribuição de alturas
calcDistAltura <- function(DadosAltura){

#monta a tabela de classes de altura
  numAlturas <- data.frame("Classe" = c(paste(as.character(round(min(DadosAltura$Altura)),1)," - ",as.character(round(mean(DadosAltura$Altura, na.rm=TRUE)-sd(DadosAltura$Altura, na.rm=TRUE), 1)),
                      sep=""),paste(as.character(round(mean(DadosAltura$Altura, na.rm=TRUE) - sd(DadosAltura$Altura, na.rm=TRUE), 1)), " - ", as.character(round(mean(DadosAltura$Altura, na.rm=TRUE) +                           sd(DadosAltura$Altura, na.rm=TRUE), 1)), sep="" ), paste( as.character(round(mean(DadosAltura$Altura, na.rm=TRUE) + sd(DadosAltura$Altura, na.rm=TRUE), 1))," - ",                                          as.character(round(max(DadosAltura$Altura, na.rm=TRUE),1)), sep="")))

  tempAlturas <- data.frame(Altura=DadosAltura$Altura, cls=0)
  tempAlturaMedia <- mean(tempAlturas$Altura, na.rm=TRUE)
  tempAlturaDesvPad <- sd(tempAlturas$Altura, na.rm = TRUE)

  tempAlturas$cls <- ifelse(tempAlturas$Altura < tempAlturaMedia - tempAlturaDesvPad, 1 , ifelse(tempAlturas$Altura >= tempAlturaMedia + tempAlturaDesvPad, 3, 2))

  tempContador <- count(tempAlturas, tempClasseNumero=cls==1)
  numAlturas[1,2] <- max(ifelse(tempContador$tempClasseNumero==TRUE, tempContador$n, 0))

  tempContador <- count(tempAlturas, tempClasseNumero=cls==2)
  numAlturas[2,2] <- max(ifelse(tempContador$tempClasseNumero==TRUE, tempContador$n, 0))

  tempContador <- count(tempAlturas, tempClasseNumero=cls==3)
  numAlturas[3,2] <- max(ifelse(tempContador$tempClasseNumero==TRUE, tempContador$n, 0))

  colnames(numAlturas)[2] <- "Num. Fustes"
  
  return(numAlturas)

}

 #monta a tabela de classes de altura
calcTabelaClasseAltura <- function(DadosAltura){
  
  tempAlturas <- data.frame(Altura=DadosAltura$Altura, cls=0)
  tempMediaAltura <- mean(tempAlturas$Altura, na.rm=TRUE)
  tempDesvPadAltura <- sd(tempAlturas$Altura, na.rm = TRUE)

  tempAlturas$cls <- ifelse(tempAlturas$Altura < tempMediaAltura - tempDesvPadAltura, 1, ifelse(tempAlturas$Altura >= tempMediaAltura+tempDesvPadAltura, 3, 2))

  colnames(tempAlturas)[2] <- "Classe"

  return(tempAlturas)
  
}

#plota o grafico de estratificação vertical
plotarEstratVertical <- function(DadosAltura){
  grafico <- (ggplot(DadosAltura, aes(c(x=1:nrow(DadosAltura)),y=DadosAltura[,1], fill=as.factor(DadosAltura[,2]) ),) + 
    geom_col() + 
    scale_fill_manual(values=c("#AA7777","#88AA88", "#447744"), labels=c("Estrato inferior", "Estrato médio", "Estrato superior")) + 
    geom_line(y=mean(DadosAltura[,1])-sd(DadosAltura[,1]), color="#885555") +
    geom_line(y=mean(DadosAltura[,1])+sd(DadosAltura[,1]), color="#557755") + 
 
    labs(title="Perfil Vertical da Floresta", x="Indivíduo", y="Altura", fill="Legenda") + 
    theme(legend.position="bottom", panel.background = element_rect(fill="#DDEEDD", colour = "#CCCCDD"), plot.title = element_text(hjust=0.5)))
    
    
   return(grafico)
}

#plota o gráfico de distribuições

  #gráfico de barras para distribuição diamétrica
  plotarGrafBarras <- function (DadosDistribuicao, eixoX, eixoY, titulo, rotuloX, rotuloY) {

  grafico <- ggplot(DadosDistribuicao, aes(eixoX, eixoY), ) + geom_col(fill="#225522", width = 0.6 ) + 
             theme(panel.background = element_rect(fill="#DDEEDD", colour="#AABBAA"), plot.title = element_text(hjust=0.5)) +
             labs(x=rotuloX, y=rotuloY) + ggtitle(titulo)
  
 
  
  return(grafico)

  }
  
  #cria a tabela de fitossociologia
calcTabelaFito <- function(DadosFito, Parametros){

  tabelaFito <- DadosFito %>% 
                  filter(Fuste==1) %>%
                  group_by(Especie) %>%
                  count
  
  tempNPO <- DadosFito %>% group_by(Especie, Parcela) %>% count
  tempNPO <- tempNPO %>% group_by(Especie) %>% count
  
  colnames(tabelaFito) <- c("Especie", "NI")   
  numParcelas <- nrow(DadosFito %>% group_by(Parcela) %>% count)
  
  tabelaFito$NPO <- as.numeric(sapply(tempNPO[2], as.integer))
  tabelaFito$DAP <- sapply(aggregate(DadosFito$DAP, by=list(DadosFito$Especie), FUN=mean)[2], as.double)
  tabelaFito$Alt <- sapply(aggregate(DadosFito$Altura, by=list(DadosFito$Especie), FUN=mean)[2], as.double)
  tabelaFito$AB <- sapply(aggregate(DadosFito$AB, by=list(DadosFito$Especie), FUN=mean)[2], as.double)
  tabelaFito$DA <- sapply((tabelaFito$NI / (numParcelas * (Parametros$AreaParc/10000))), as.double)
  tabelaFito$DR <- tabelaFito$DA / sum(tabelaFito$DA)
  tabelaFito$DoA <- sapply((tabelaFito$AB / (numParcelas * (Parametros$AreaParc/10000))), as.double)
  tabelaFito$DoR <- tabelaFito$DoA / sum(tabelaFito$DoA)
  tabelaFito$FA <- sapply((tabelaFito$NPO / numParcelas), as.numeric)
  tabelaFito$FR <- tabelaFito$FA / sum(tabelaFito$FA)
  tabelaFito$FA <- sapply((tabelaFito$NPO / numParcelas), as.numeric)
  tabelaFito$FR <- tabelaFito$FA / sum(tabelaFito$FA)
  tabelaFito$IVI <- tabelaFito$DR + tabelaFito$DoR + tabelaFito$FR
  tabelaFito$IVIR <- tabelaFito$IVI / sum(tabelaFito$IVI)
  
  tabelaTotal <- data.frame(Especie = "Total", 
                            NI = sum(tabelaFito$NI), 
                            NPO = numParcelas, 
                            DAP = mean(tabelaFito$DAP), 
                            Alt = mean(tabelaFito$Alt),
                            AB = sum(tabelaFito$AB),
                            DA = sum(tabelaFito$DA),
                            DR = sum(tabelaFito$DR),
                            DoA = sum(tabelaFito$DoA),
                            DoR = sum(tabelaFito$DoR),
                            FA = sum(tabelaFito$FA),
                            FR = sum(tabelaFito$FR),
                            IVI = sum(tabelaFito$IVI),
                            IVIR = sum(tabelaFito$IVIR)
                            )
  
  
  tabelaFito <- bind_rows(tabelaFito, tabelaTotal)
  
  tabelaFito$DAP <- as.numeric(round(tabelaFito$DAP, 1))
  tabelaFito$Alt <- as.numeric(round(tabelaFito$Alt, 1))
  tabelaFito$AB <- as.numeric(round(tabelaFito$AB, 5))
  tabelaFito$DA <- round(tabelaFito$DA, 5)
  tabelaFito$DR <- round(tabelaFito$DR, 4)
  tabelaFito$DoA <- round(tabelaFito$DoA, 5)
  tabelaFito$DoR <- round(tabelaFito$DoR, 4)
  tabelaFito$FA <- round(tabelaFito$FA, 4)
  tabelaFito$FR <- round(tabelaFito$FR, 4)
  tabelaFito$IVI <- round(tabelaFito$IVI, 4)
  tabelaFito$IVIR <- round(tabelaFito$IVIR, 4)
  
  colnames(tabelaFito) <- c("Espécie", "NI", "NPO", "DAP Médio", "Alt. Média", "AB", "DA", "DR", "DoA", "DoR", "FA", "FR", "IVI", "IVI %")

  return(tabelaFito)
}


salvarXLSX <- function(DadosBrutos, VolParcela, Volumetria, DistDiam, DistAlt, Fitossociologia, GrafDistDiam, GrafDistAlt, GrafEstrato) {
  
  Workbook <- openxlsx::createWorkbook()
  
  addWorksheet(Workbook, "Dados")
  addWorksheet(Workbook, "Volumetria")
  addWorksheet(Workbook, "Perfil")
  addWorksheet(Workbook, "Fitossociologia")
  
  numFormat = "0.0%"
  
  headerStyle <- createStyle(fontColour = "#000000", halign = "center", fgFill = "#99BB99", border = "TopBottom", borderColour = "#000000")
  
  bodyBottomStyle <- createStyle(fontColour = "#000000", fgFill = "#FFFFFF", border="Bottom", borderColour = "#000000") #estilo do corpo 1
  
  bodyBottomStylePerc <- createStyle(fontColour = "#000000", numFmt = numFormat, fgFill = "#FFFFFF", border="Bottom", borderColour = "#000000") #estilo do corpo 1
 
  bodyTopBottomStyle <- createStyle(fontColour = "#000000", fgFill = "#FFFFFF", border="TopBottom", borderColour = "#000000") #estilo do corpo 2
  
  bodyTopBottomStylePerc <- createStyle(fontColour = "#000000", numFmt = numFormat, fgFill = "#FFFFFF", border="TopBottom", borderColour = "#000000") #estilo do corpo 2

  bodyNoneStyle <- createStyle(fontColour = "#000000", fgFill = "#FFFFFF", borderStyle="none", borderColour = "#000000") #estilo do corpo 3
  
  bodyNoneStylePerc <- createStyle(fontColour = "#000000", fgFill = "#FFFFFF", borderStyle="none", numFmt = numFormat, borderColour = "#000000") #estilo do corpo 3
  
  
  
  #inicio da escrita de Dados

  writeData(Workbook, "Dados", DadosBrutos, 1, 1, colNames=TRUE)
  
  addStyle(Workbook, sheet = "Dados", headerStyle, rows = 1, cols=1:ncol(DadosBrutos), gridExpand = TRUE)
  
  addStyle(Workbook, sheet = "Dados", bodyNoneStyle, rows = 2:nrow(DadosBrutos), cols=1:ncol(DadosBrutos), gridExpand = TRUE)
  
  addStyle(Workbook, sheet = "Dados", bodyBottomStyle, rows = nrow(DadosBrutos)+1, cols=1:ncol(DadosBrutos), gridExpand = TRUE)
 
 setColWidths(Workbook, "Dados", cols = 1:ncol(DadosBrutos), widths = "auto")
  
  #inicio da escrita de volumetria
  
  writeData(Workbook, "Volumetria", VolParcela, 1, 1, colNames=TRUE)
  
  addStyle(Workbook, sheet = "Volumetria", headerStyle, rows = 1, cols=1:ncol(VolParcela), gridExpand = TRUE)
  
  addStyle(Workbook, sheet = "Volumetria", bodyNoneStyle, rows = 2:nrow(VolParcela), cols=1:ncol(VolParcela), gridExpand = TRUE)
  
  addStyle(Workbook, sheet = "Volumetria", bodyBottomStyle, rows = nrow(VolParcela)+1, cols=1:ncol(VolParcela), gridExpand = TRUE)
 
 setColWidths(Workbook, "Volumetria", cols = 1:ncol(VolParcela), widths = "auto")
  
  
  writeData(Workbook, "Volumetria", Volumetria, (ncol(VolParcela) + 2), 1, colNames=TRUE)
  
  addStyle(Workbook, sheet = "Volumetria", headerStyle, rows = 1, cols=(ncol(VolParcela) + 2):(ncol(VolParcela) + 2 +ncol(VolParcela)), gridExpand = TRUE)
  
  addStyle(Workbook, sheet = "Volumetria", bodyNoneStyle, rows = 2:nrow(Volumetria), cols=(ncol(VolParcela) + 2):(ncol(VolParcela) + 2 +ncol(VolParcela)), gridExpand = TRUE)
  
  addStyle(Workbook, sheet = "Volumetria", bodyBottomStyle, rows = nrow(Volumetria)+1, cols=(ncol(VolParcela) + 2):(ncol(VolParcela) + 2 +ncol(VolParcela)), gridExpand = TRUE)
 
 setColWidths(Workbook, "Volumetria", cols = (ncol(VolParcela) + 2):(ncol(VolParcela) + 2 +ncol(VolParcela)), widths = "auto")
  
  
  #inicio da escrita do perfil
  
  writeData(Workbook, "Perfil", DistDiam, 1, 1, colNames=TRUE)
  
  addStyle(Workbook, sheet = "Perfil", headerStyle, rows = 1, cols=1:ncol(DistDiam), gridExpand = TRUE)
  
  addStyle(Workbook, sheet = "Perfil", bodyNoneStyle, rows = 2:nrow(DistDiam), cols=1:ncol(DistDiam), gridExpand = TRUE)
  
  addStyle(Workbook, sheet = "Perfil", bodyTopBottomStyle, rows = nrow(DistDiam)+1, cols=1:ncol(DistDiam), gridExpand = TRUE)
 
 setColWidths(Workbook, "Perfil", cols = 1:ncol(DistDiam), widths = "auto")
  
 
  writeData(Workbook, "Perfil", DistAlt, 1, nrow(DistDiam) + 4, colNames=TRUE)
  
  addStyle(Workbook, sheet = "Perfil", headerStyle, rows = (nrow(DistDiam) + 4), cols=1:ncol(DistAlt), gridExpand = TRUE)
  
  addStyle(Workbook, sheet = "Perfil", bodyNoneStyle, rows = (nrow(DistDiam) + 5):(nrow(DistDiam) + 4 + nrow(DistAlt)), cols=1:ncol(DistAlt), gridExpand = TRUE)
  
  addStyle(Workbook, sheet = "Perfil", bodyBottomStyle, rows = (nrow(DistDiam) + 4 + nrow(DistAlt)), cols=1:ncol(DistAlt), gridExpand = TRUE)
 
 setColWidths(Workbook, "Perfil", cols = 1:ncol(DistAlt), widths = "auto")
  
  insertImage(Workbook, "Perfil", "GrafDistDiam.png", 6, 4, startCol = 4, startRow = 2)
  insertImage(Workbook, "Perfil", "GrafDistAlt.png", 6, 4, startCol = 12, startRow = 2)
  insertImage(Workbook, "Perfil", "GrafEstrAlt.png", 6, 4, startCol = 4, startRow = 23)
  
  #inicio da escrita da fitossociologia
  
  writeData(Workbook, "Fitossociologia", Fitossociologia, 1, 1, colNames=TRUE)
  
    addStyle(Workbook, sheet = "Fitossociologia", headerStyle, rows = 1, cols=1:ncol(Fitossociologia), gridExpand = TRUE)
  
  addStyle(Workbook, sheet = "Fitossociologia", bodyNoneStyle, rows = 2:nrow(Fitossociologia), cols=1:ncol(Fitossociologia), gridExpand = TRUE)
  
  addStyle(Workbook, sheet = "Fitossociologia", bodyNoneStylePerc, rows = 2:nrow(Fitossociologia), cols=c(8, 10, 11, 12, 13, 14), gridExpand = TRUE)
  
  addStyle(Workbook, sheet = "Fitossociologia", bodyTopBottomStyle, rows = nrow(Fitossociologia)+1, cols=1:ncol(Fitossociologia), gridExpand = TRUE)
  
  addStyle(Workbook, sheet = "Fitossociologia", bodyTopBottomStylePerc, rows = nrow(Fitossociologia)+1, cols=c(8, 10, 11, 12, 13, 14), gridExpand = TRUE)
 
  setColWidths(Workbook, "Fitossociologia", cols = 1:ncol(Fitossociologia), widths = "auto")
  
  #salvar o arquivo
  saveWorkbook(Workbook, "ACS-Resultado.xlsx", overwrite = TRUE)
  
}

```

```{r}

#Corpo principal

#importação dos dados

DadosImportados <- ImportarDados()
DadosImportados <- calcDAV(DadosImportados)
DadosVol <- calcVolumeTab(DadosImportados)

Parametros <- receberParametros()
Volumetria <- calcParamInventario(DadosVol, Parametros)
DistDiametrica <- calcDistDiametrica(DadosImportados)
DistAltura <- calcDistAltura(DadosImportados)

png(filename = "GrafEstrAlt.png", height = 400, width = 600)
  GraficoEstratoAltura <- plotarEstratVertical(calcTabelaClasseAltura(DadosImportados))
  print(GraficoEstratoAltura)
dev.off()

png("GrafDistAlt.png", height = 400, width = 600) 
  tempDistAlturas <- data.frame(X=factor(DistAltura[1:3,1], levels = DistAltura[1:3,1]), Y=as.numeric(DistAltura[1:3,2]))
  GraficoClasseAltura <- plotarGrafBarras(tempDistAlturas, tempDistAlturas$X, tempDistAlturas$Y, "Distribuição Hipsométrica", "Classe (m)", "Num. Fustes") #chama a função
  print(GraficoClasseAltura)
dev.off()

png("GrafDistDiam.png", height = 400, width = 600)
  tempDistDiam <- data.frame(X=factor(DistDiametrica[1:nrow(DistDiametrica)-1,1], levels = DistDiametrica[1:nrow(DistDiametrica)-1,1]), Y=as.numeric(DistDiametrica[1:nrow(DistDiametrica)-1,2]))
  GraficoClasseDiametro <- plotarGrafBarras(tempDistDiam, tempDistDiam$X, tempDistDiam$Y, "Distribuição Diamétrica", "Classe (cm)", "Num. Fustes") #chama a função
  print(GraficoClasseDiametro)
dev.off()

Fitossociologia <- calcTabelaFito(DadosImportados, Parametros) #chama a função de fitossociologia

salvarXLSX(DadosImportados, DadosVol, Volumetria, DistDiametrica, DistAltura, Fitossociologia, GraficoClasseDiametro, GraficoClasseAltura, GraficoEstratoAltura)

```

